// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: transactionmessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from transactionmessage.proto</summary>
public static partial class TransactionmessageReflection {

  #region Descriptor
  /// <summary>File descriptor for transactionmessage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static TransactionmessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Chh0cmFuc2FjdGlvbm1lc3NhZ2UucHJvdG8iGQoJQnl0ZUFycmF5EgwKBGRh",
          "dGEYASABKAwixgEKEFByb3RvVHJhbnNhY3Rpb24SDwoHdmVyc2lvbhgBIAEo",
          "DRINCgVub25jZRgCIAEoBBIOCgZ0b2FkZHIYAyABKAwSGgoGcHVia2V5GAQg",
          "ASgLMgouQnl0ZUFycmF5EhoKBmFtb3VudBgFIAEoCzIKLkJ5dGVBcnJheRIc",
          "CghnYXNwcmljZRgGIAEoCzIKLkJ5dGVBcnJheRIQCghnYXNsaW1pdBgHIAEo",
          "BBIMCgRjb2RlGAggASgMEgwKBGRhdGEYCSABKAxiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ByteArray), global::ByteArray.Parser, new[]{ "Data" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoTransaction), global::ProtoTransaction.Parser, new[]{ "Version", "Nonce", "Toaddr", "Pubkey", "Amount", "Gasprice", "Gaslimit", "Code", "Data" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ByteArray : pb::IMessage<ByteArray>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ByteArray> _parser = new pb::MessageParser<ByteArray>(() => new ByteArray());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ByteArray> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TransactionmessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ByteArray() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ByteArray(ByteArray other) : this() {
    data_ = other.data_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ByteArray Clone() {
    return new ByteArray(this);
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 1;
  private pb::ByteString data_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Data {
    get { return data_; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ByteArray);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ByteArray other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Data != other.Data) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Data.Length != 0) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Data.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Data.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Data.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ByteArray other) {
    if (other == null) {
      return;
    }
    if (other.Data.Length != 0) {
      Data = other.Data;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Data = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Data = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class ProtoTransaction : pb::IMessage<ProtoTransaction>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ProtoTransaction> _parser = new pb::MessageParser<ProtoTransaction>(() => new ProtoTransaction());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ProtoTransaction> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TransactionmessageReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoTransaction() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoTransaction(ProtoTransaction other) : this() {
    version_ = other.version_;
    nonce_ = other.nonce_;
    toaddr_ = other.toaddr_;
    pubkey_ = other.pubkey_ != null ? other.pubkey_.Clone() : null;
    amount_ = other.amount_ != null ? other.amount_.Clone() : null;
    gasprice_ = other.gasprice_ != null ? other.gasprice_.Clone() : null;
    gaslimit_ = other.gaslimit_;
    code_ = other.code_;
    data_ = other.data_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ProtoTransaction Clone() {
    return new ProtoTransaction(this);
  }

  /// <summary>Field number for the "version" field.</summary>
  public const int VersionFieldNumber = 1;
  private uint version_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Version {
    get { return version_; }
    set {
      version_ = value;
    }
  }

  /// <summary>Field number for the "nonce" field.</summary>
  public const int NonceFieldNumber = 2;
  private ulong nonce_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Nonce {
    get { return nonce_; }
    set {
      nonce_ = value;
    }
  }

  /// <summary>Field number for the "toaddr" field.</summary>
  public const int ToaddrFieldNumber = 3;
  private pb::ByteString toaddr_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Toaddr {
    get { return toaddr_; }
    set {
      toaddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "pubkey" field.</summary>
  public const int PubkeyFieldNumber = 4;
  private global::ByteArray pubkey_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ByteArray Pubkey {
    get { return pubkey_; }
    set {
      pubkey_ = value;
    }
  }

  /// <summary>Field number for the "amount" field.</summary>
  public const int AmountFieldNumber = 5;
  private global::ByteArray amount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ByteArray Amount {
    get { return amount_; }
    set {
      amount_ = value;
    }
  }

  /// <summary>Field number for the "gasprice" field.</summary>
  public const int GaspriceFieldNumber = 6;
  private global::ByteArray gasprice_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ByteArray Gasprice {
    get { return gasprice_; }
    set {
      gasprice_ = value;
    }
  }

  /// <summary>Field number for the "gaslimit" field.</summary>
  public const int GaslimitFieldNumber = 7;
  private ulong gaslimit_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Gaslimit {
    get { return gaslimit_; }
    set {
      gaslimit_ = value;
    }
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 8;
  private pb::ByteString code_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Code {
    get { return code_; }
    set {
      code_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "data" field.</summary>
  public const int DataFieldNumber = 9;
  private pb::ByteString data_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Data {
    get { return data_; }
    set {
      data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ProtoTransaction);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ProtoTransaction other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Version != other.Version) return false;
    if (Nonce != other.Nonce) return false;
    if (Toaddr != other.Toaddr) return false;
    if (!object.Equals(Pubkey, other.Pubkey)) return false;
    if (!object.Equals(Amount, other.Amount)) return false;
    if (!object.Equals(Gasprice, other.Gasprice)) return false;
    if (Gaslimit != other.Gaslimit) return false;
    if (Code != other.Code) return false;
    if (Data != other.Data) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Version != 0) hash ^= Version.GetHashCode();
    if (Nonce != 0UL) hash ^= Nonce.GetHashCode();
    if (Toaddr.Length != 0) hash ^= Toaddr.GetHashCode();
    if (pubkey_ != null) hash ^= Pubkey.GetHashCode();
    if (amount_ != null) hash ^= Amount.GetHashCode();
    if (gasprice_ != null) hash ^= Gasprice.GetHashCode();
    if (Gaslimit != 0UL) hash ^= Gaslimit.GetHashCode();
    if (Code.Length != 0) hash ^= Code.GetHashCode();
    if (Data.Length != 0) hash ^= Data.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Version != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Version);
    }
    if (Nonce != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(Nonce);
    }
    if (Toaddr.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(Toaddr);
    }
    if (pubkey_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Pubkey);
    }
    if (amount_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Amount);
    }
    if (gasprice_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(Gasprice);
    }
    if (Gaslimit != 0UL) {
      output.WriteRawTag(56);
      output.WriteUInt64(Gaslimit);
    }
    if (Code.Length != 0) {
      output.WriteRawTag(66);
      output.WriteBytes(Code);
    }
    if (Data.Length != 0) {
      output.WriteRawTag(74);
      output.WriteBytes(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Version != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Version);
    }
    if (Nonce != 0UL) {
      output.WriteRawTag(16);
      output.WriteUInt64(Nonce);
    }
    if (Toaddr.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(Toaddr);
    }
    if (pubkey_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Pubkey);
    }
    if (amount_ != null) {
      output.WriteRawTag(42);
      output.WriteMessage(Amount);
    }
    if (gasprice_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(Gasprice);
    }
    if (Gaslimit != 0UL) {
      output.WriteRawTag(56);
      output.WriteUInt64(Gaslimit);
    }
    if (Code.Length != 0) {
      output.WriteRawTag(66);
      output.WriteBytes(Code);
    }
    if (Data.Length != 0) {
      output.WriteRawTag(74);
      output.WriteBytes(Data);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Version != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Version);
    }
    if (Nonce != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Nonce);
    }
    if (Toaddr.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Toaddr);
    }
    if (pubkey_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pubkey);
    }
    if (amount_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Amount);
    }
    if (gasprice_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gasprice);
    }
    if (Gaslimit != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Gaslimit);
    }
    if (Code.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Code);
    }
    if (Data.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ProtoTransaction other) {
    if (other == null) {
      return;
    }
    if (other.Version != 0) {
      Version = other.Version;
    }
    if (other.Nonce != 0UL) {
      Nonce = other.Nonce;
    }
    if (other.Toaddr.Length != 0) {
      Toaddr = other.Toaddr;
    }
    if (other.pubkey_ != null) {
      if (pubkey_ == null) {
        Pubkey = new global::ByteArray();
      }
      Pubkey.MergeFrom(other.Pubkey);
    }
    if (other.amount_ != null) {
      if (amount_ == null) {
        Amount = new global::ByteArray();
      }
      Amount.MergeFrom(other.Amount);
    }
    if (other.gasprice_ != null) {
      if (gasprice_ == null) {
        Gasprice = new global::ByteArray();
      }
      Gasprice.MergeFrom(other.Gasprice);
    }
    if (other.Gaslimit != 0UL) {
      Gaslimit = other.Gaslimit;
    }
    if (other.Code.Length != 0) {
      Code = other.Code;
    }
    if (other.Data.Length != 0) {
      Data = other.Data;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Version = input.ReadUInt32();
          break;
        }
        case 16: {
          Nonce = input.ReadUInt64();
          break;
        }
        case 26: {
          Toaddr = input.ReadBytes();
          break;
        }
        case 34: {
          if (pubkey_ == null) {
            Pubkey = new global::ByteArray();
          }
          input.ReadMessage(Pubkey);
          break;
        }
        case 42: {
          if (amount_ == null) {
            Amount = new global::ByteArray();
          }
          input.ReadMessage(Amount);
          break;
        }
        case 50: {
          if (gasprice_ == null) {
            Gasprice = new global::ByteArray();
          }
          input.ReadMessage(Gasprice);
          break;
        }
        case 56: {
          Gaslimit = input.ReadUInt64();
          break;
        }
        case 66: {
          Code = input.ReadBytes();
          break;
        }
        case 74: {
          Data = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Version = input.ReadUInt32();
          break;
        }
        case 16: {
          Nonce = input.ReadUInt64();
          break;
        }
        case 26: {
          Toaddr = input.ReadBytes();
          break;
        }
        case 34: {
          if (pubkey_ == null) {
            Pubkey = new global::ByteArray();
          }
          input.ReadMessage(Pubkey);
          break;
        }
        case 42: {
          if (amount_ == null) {
            Amount = new global::ByteArray();
          }
          input.ReadMessage(Amount);
          break;
        }
        case 50: {
          if (gasprice_ == null) {
            Gasprice = new global::ByteArray();
          }
          input.ReadMessage(Gasprice);
          break;
        }
        case 56: {
          Gaslimit = input.ReadUInt64();
          break;
        }
        case 66: {
          Code = input.ReadBytes();
          break;
        }
        case 74: {
          Data = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
